class NetworkNames(str):
    Ethereum = 'Ethereum'
    Arbitrum = 'Arbitrum'
    Arbitrum_Nova = 'Arbitrum_Nova'
    Avalanche = 'Avalanche'
    Base = 'Base'
    BSC = 'BSC'
    Celo = 'Celo'
    Core = 'Core'
    Fantom = 'Fantom'
    Gnosis = 'Gnosis'
    Heco = 'Heco'
    Kava = 'Kava'
    Mantle = 'Mantle'
    Moonbeam = 'Moonbeam'
    opBNB = 'opBNB'
    Optimism = 'Optimism'
    Polygon = 'Polygon'
    zkSync_Era = 'zkSync_Era'

    Goerli = 'Goerli'
    Sepolia = 'Sepolia'
    Holesky = 'Holesky'
    
    Starknet = 'Starknet'
