from .common import strEnum


class TokenSymbol(strEnum):
    ETH = 'ETH'

    ARB = 'ARB'
    AVAX = 'AVAX'
    BNB = 'BNB'
    BTC_B = 'BTC_B'
    BUSD = 'BUSD'
    CELO = 'CELO'
    CORE = 'CORE'
    DAI = 'DAI'
    FRAX = 'FRAX'
    FTM = 'FTM'
    GETH = 'GETH'
    GETH_LZ = 'GETH_LZ'
    GLMR = 'GLMR'
    HECO = 'HECO'
    KAVA = 'KAVA'
    POL = 'POL'
    STG = 'STG'
    USDT = 'USDT'
    USDC = 'USDC'
    USDC_E = 'USDC_E'
    USDV = 'USDV'
    WBTC = 'WBTC'
    WCORE = 'WCORE'
    WETH = 'WETH'
    XDAI = 'xDAI'
    ZRO = 'ZRO'
    SPACE = 'SPACE'
    STRK = 'STRK'
