from abc import ABC
from typing import List, Type

from sqlalchemy import select, insert
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from ._generic import TEntity, GenericRepository


class SqlAlchemyRepository(GenericRepository[TEntity], ABC):
    def __init__(
        self, 
        session: AsyncSession, 
        entity_type: Type[TEntity]
    ):
        self.__session = session
        self.entity_type = entity_type

    async def get_by_id(self, id: int) -> TEntity | None:
        return await self.get_with_filters({'id': id})

    async def get_with_filters(
        self, 
        filter_dict: dict
    ) -> TEntity | None:
        try:
            query = select(self.entity_type).filter_by(**filter_dict).limit(1)
            result = await self.__session.execute(query)
            record = result.scalar_one_or_none()
            return record
        except SQLAlchemyError as e:
            raise 

    async def get_all(self) -> List[TEntity] | None:
        return await self.get_all_with_filters()

    async def get_all_with_filters(
        self, 
        filter_dict: dict
    ) -> List[TEntity] | None:
        try:
            query = select(self.entity_type).filter_by(**filter_dict)
            result = await self.__session.execute(query)
            records = result.scalars().all()
            return records
        except SQLAlchemyError as e:
            raise

    async def add(self, entity: TEntity) -> int:
        """
        Adds a new entity to the database.

        This method adds the provided entity to the session and flushes the session to 
        ensure the entity is persisted in the database. If the entity has an id specified, 
        it will be added with that id. Otherwise, a new id will be generated by the database.

        Args:
            entity (Model): The entity to be added to the database.

        Returns:
            int: The id of the added entity.
        """
        self.__session.add(entity)
        try:
            await self.__session.flush()
        except SQLAlchemyError as e:
            await self.__session.rollback()
            raise e
        return entity.id
        
    async def _execute_insert_some(
        self, 
        entities: List[TEntity], 
        returning: bool
    ) -> List[TEntity] | None:
        values = [entity.__dict__.items() for entity in entities]
        
        try:
            command = insert(self.entity_type).execution_options(render_nulls=True)
            if returning:
                command = command.returning(self.entity_type)
                
            result = await self.__session.execute(statement=command, params=[*values]) 
            await self.__session.flush()
            return (
                result.scalars().all()
                if returning
                else [entity.id for entity in entities]
            )
            
        except IntegrityError as e:
            str_error = str(e.orig)
            if 'UNIQUE constraint failed:' in str_error:
                constraint_name = str_error.split('UNIQUE constraint failed: ')[-1]
                raise(
                    "Can't add entity with the same"
                    f" value in {constraint_name}"
                )
            await self.__session.rollback()    

    async def add_all(
        self, 
        entities: List[TEntity]
    ) -> List[int]:
        """
        Adds a list of entities to the database.
        This method takes a list of entities, adds them to the session, and 
        flushes the session to ensure they are persisted in the database. 

        It returns a list of ids of the added entities.

        Args:
            entities (List[Model]): A list of entities to be added to the database.

        Returns:
            List[int]: A list of ids of the added entities.
        """
        return await self._execute_insert_some(entities, False)

    async def add_all_and_return(
        self, 
        entities: List[TEntity]
    ) -> List[TEntity]:
        """
        Adds multiple entities to the database and returns them.

        This method takes a list of entities, adds them to the session, and 
        flushes the session to ensure they are persisted in the database. 
        It returns a list of the added entities.

        Args:
            entities (List[Model]): A list of entities to be added to the database.

        Returns:
            List[Model]: A list of the added entities.
        """
        return await self._execute_insert_some(entities, True)

    async def update(self, entity: TEntity) -> int:
        """
        Updates an existing entity with id (!) or creates a new one if it does not exist.

        This method uses the SQLAlchemy `merge` function to either update an existing 
        entity with the same id in the database or create a new entity if no such 
        entity exists. Return id

        Args:
            entity (Model): The entity to be updated or created.

        Returns:
            int: The updated or newly created entity's id.
        """
        await self.__session.merge(entity)
        await self.__session.commit()
        return entity.id

    async def delete(self, id: int) -> bool:
        db_record = await self.get_by_id(id)
        if not db_record: 
            return False
        
        await self.__session.delete(db_record)
        await self.__session.commit()
        return True